import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('catalog, live search, empty state, responsive layout and accessibility',async({page})=>{
 await page.goto('/');
 await expect(page.locator('.restaurant-card')).toHaveCount(5);
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.getByRole('searchbox').fill('italian');
 await expect(page.locator('.restaurant-card')).toHaveCount(1);
 await expect(page.getByRole('button',{name:'Zeppoli’s',exact:true})).toBeVisible();
 await page.getByRole('searchbox').fill('nothing-matches-xyz');
 await expect(page.getByText('No spots found this time.')).toBeVisible();
 await page.getByRole('button',{name:'Show all restaurants'}).click();
 await expect(page.locator('.restaurant-card')).toHaveCount(5);
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.getByRole('button',{name:'Cabo Fish Taco',exact:true}).click();
 await expect(page.getByRole('dialog').getByRole('heading',{name:'Cabo Fish Taco',exact:true})).toBeVisible();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.keyboard.press('Escape');
 await expect(page.getByRole('dialog')).not.toBeVisible();
});

test('register, persist session, create/edit/delete review, and sign in again',async({page})=>{
 const email=`test-${Date.now()}@example.com`;
 await page.goto('/');
 await page.getByRole('button',{name:'Join the table'}).click();
 await page.getByLabel('Display name').fill('Test Foodie');
 await page.getByLabel('Email address').fill(email);
 await page.getByLabel('Password',{exact:true}).fill('demo-password-123');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();
 await page.getByRole('button',{name:'Cabo Fish Taco',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Write a review',exact:false}).click();
 await page.getByRole('radio',{name:'5 stars'}).check();
 await page.getByLabel('Your review',{exact:true}).fill('A wonderful meal with friends. Would absolutely visit again.');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.getByRole('button',{name:'Publish review'}).click();
 await expect(page.getByText('A wonderful meal with friends. Would absolutely visit again.')).toBeVisible();
 await expect(page.getByText('5 community reviews')).toBeVisible();
 await page.getByRole('button',{name:'Edit your review'}).click();
 await page.getByRole('radio',{name:'3 stars'}).check();
 await page.getByLabel('Your review',{exact:true}).fill('Updated review: a pleasant evening and a good meal.');
 await page.getByRole('button',{name:'Save changes'}).click();
 await expect(page.getByText('Updated review: a pleasant evening and a good meal.')).toBeVisible();
 await expect(page.getByText('5 community reviews')).toBeVisible();
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'My reviews',exact:true}).click();
 await expect(page.getByText('Updated review: a pleasant evening and a good meal.')).toBeVisible();
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Sign out'}).click();
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByLabel('Email address').fill(email);
 await page.getByLabel('Password',{exact:true}).fill('wrong-password');
 await page.getByRole('button',{name:'Sign in',exact:true}).last().click();
 await expect(page.getByRole('alert')).toHaveText('Email or password is incorrect.');
 await page.getByLabel('Password',{exact:true}).fill('demo-password-123');
 await page.getByRole('button',{name:'Sign in',exact:true}).last().click();
 await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();
 await page.getByRole('button',{name:'Cabo Fish Taco',exact:true}).click();
 await page.getByRole('button',{name:'Edit your review'}).click();
 await page.getByRole('button',{name:'Delete review',exact:true}).click();
 await page.getByRole('button',{name:'Yes, delete my review'}).click();
 await expect(page.getByText('4 community reviews')).toBeVisible();
 await expect(page.getByText('Updated review: a pleasant evening and a good meal.')).toHaveCount(0);
});

test('demo onboarding and server validation prevent unauthorized changes',async({page,request})=>{
 const privateFile=await request.get('/data/eats.sqlite');expect(privateFile.status()).toBe(403);
 const res=await request.post('/api/restaurants/1/reviews',{data:{rating:5,body:'Unauthorized review attempt.'}});expect(res.status()).toBe(401);
 await page.goto('/');await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('button',{name:'Try the demo account'}).click();
 await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();
 const invalid=await page.request.post('/api/restaurants/1/reviews',{data:{rating:6,body:'Invalid rating test.'}});expect(invalid.status()).toBe(400);
 const origin=await page.request.post('/api/logout',{headers:{Origin:'https://evil.example'}});expect(origin.status()).toBe(403);
 const before=await(await page.request.get('/api/restaurants/1/reviews')).json();
 await page.request.delete('/api/restaurants/1/reviews');
 const after=await(await page.request.get('/api/restaurants/1/reviews')).json();expect(after.length).toBe(before.length);
 const payload='<img src=x onerror=alert(1)> A literal review.';
 await page.request.post('/api/restaurants/1/reviews',{data:{rating:4,body:payload}});
 await page.getByRole('button',{name:'Cabo Fish Taco',exact:true}).click();
 await expect(page.getByText(payload,{exact:true})).toBeVisible();
 await expect(page.locator('#modal-content img')).toHaveCount(0);
});

test('map markers open reviews, follow searches and remain keyboard accessible',async({page})=>{
 await page.goto('/');
 await expect(page.locator('.restaurant-pin')).toHaveCount(5);
 const restaurants=await(await page.request.get('/api/restaurants')).json();
 expect(restaurants.every(r=>r.address&&r.lat>37.20&&r.lat<37.25&&r.lng>-80.45&&r.lng<-80.39)).toBeTruthy();
 await page.locator('.restaurant-pin').filter({hasText:'1'}).click();
 await expect(page.getByRole('dialog').getByRole('heading',{name:'Cabo Fish Taco',exact:true})).toBeVisible();
 await expect(page.getByText('117 South Main Street, Blacksburg, VA 24060',{exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:'Get directions'})).toHaveAttribute('href',/destination=117%20South%20Main/);
 await expect(page.getByText(`${restaurants.find(r=>r.id===1).count} community reviews`)).toBeVisible();
 await page.keyboard.press('Escape');
 await page.locator('#map-panel').screenshot({path:'test-results/map-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Fit restaurants'}).click();
 const bounds=await page.locator('#restaurant-map').boundingBox();
 for(const marker of await page.locator('.restaurant-pin').all()){
   const box=await marker.boundingBox();
   expect(box.x).toBeGreaterThanOrEqual(bounds.x);
   expect(box.y).toBeGreaterThanOrEqual(bounds.y);
   expect(box.x+box.width).toBeLessThanOrEqual(bounds.x+bounds.width);
   expect(box.y+box.height).toBeLessThanOrEqual(bounds.y+bounds.height);
 }
 await page.locator('#map-panel').screenshot({path:'test-results/map-mobile.png'});
 await page.getByRole('searchbox').fill('1329');
 await expect(page.locator('.restaurant-pin')).toHaveCount(1);
 await expect(page.locator('.restaurant-card')).toHaveCount(1);
 await page.locator('.restaurant-pin').focus();await page.keyboard.press('Enter');
 await expect(page.getByRole('dialog').getByRole('heading',{name:'Our Daily Bread',exact:true})).toBeVisible();
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Hide map',exact:true}).click();
 await expect(page.locator('#map-panel')).toBeHidden();
 await page.getByRole('searchbox').fill('gillies');
 await expect(page.locator('.restaurant-card')).toHaveCount(1);
 await page.getByRole('button',{name:'Show map',exact:true}).click();
 await expect(page.locator('.restaurant-pin')).toHaveCount(1);
 await expect(page.locator('.restaurant-pin')).toHaveAttribute('aria-label',/Gillies/);
 await page.locator('.restaurant-pin').focus();await page.keyboard.press('Space');
 await expect(page.getByRole('dialog').getByRole('heading',{name:'Gillies',exact:true})).toBeVisible();
 await page.keyboard.press('Escape');
 await page.getByRole('searchbox').fill('nonexistent xyz');
 await expect(page.locator('.restaurant-pin')).toHaveCount(0);
 await expect(page.locator('#map-empty')).toBeVisible();
 await expect(page.getByRole('button',{name:'Fit restaurants'})).toBeDisabled();
});

test('map tile failure preserves restaurant access on mobile',async({page})=>{
 await page.route('https://tile.openstreetmap.org/**',route=>route.abort());
 await page.setViewportSize({width:390,height:844});
 await page.goto('/');
 await expect(page.locator('.restaurant-pin')).toHaveCount(5);
 await expect(page.locator('#map-status')).toBeVisible();
 await page.getByRole('button',{name:'Fit restaurants'}).click();
 await page.locator('.restaurant-pin').filter({hasText:'4'}).click();
 await expect(page.getByRole('dialog').getByRole('heading',{name:'Zeppoli’s',exact:true})).toBeVisible();
 await page.keyboard.press('Escape');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
