import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('favorites, tags, category scores, photos and earned badges work together',async({page})=>{
 await page.goto('/');
 await page.request.post('/api/demo');await page.reload();
 await expect(page.locator('.restaurant-card')).toHaveCount(24);
 await page.getByRole('button',{name:'Save Gillies to favorites',exact:true}).click();
 await expect(page.getByRole('button',{name:'Remove Gillies from favorites',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'♡ Favorites',exact:true}).click();
 await expect(page.locator('.restaurant-card')).toHaveCount(1);
 await expect(page.locator('.restaurant-pin')).toHaveCount(1);
 await page.reload();
 await expect(page.getByRole('button',{name:'Remove Gillies from favorites',exact:true})).toBeVisible();
 await page.getByLabel('Restaurant tag',{exact:true}).selectOption('Vegetarian');
 await expect(page.locator('.restaurant-card')).toHaveCount(1);
 await page.getByRole('button',{name:'Gillies',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Write a review'}).click();
 await page.getByRole('radio',{name:'4 stars'}).check();
 await page.getByLabel('Food quality',{exact:true}).selectOption('5');
 await page.getByLabel('Service',{exact:true}).selectOption('3');
 await page.getByLabel('Atmosphere',{exact:true}).selectOption('4');
 await page.getByLabel('Your review',{exact:true}).fill('A thoughtful vegetarian menu and a relaxing lunch.');
 await page.getByRole('button',{name:'Publish review'}).click();
 await expect(page.locator('.category-summary')).toContainText('5.0 / 5');
 await expect(page.locator('.review-categories')).toContainText(['Food quality: 5/5']);
 await page.getByRole('button',{name:'Edit your review'}).click();
 await expect(page.getByLabel('Service',{exact:true})).toHaveValue('3');
 await page.getByLabel('Service',{exact:true}).selectOption('4');
 await page.getByRole('button',{name:'Save changes'}).click();
 await page.getByRole('button',{name:'Add photo',exact:true}).click();
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=100;c.height=80;c.getContext('2d').fillRect(0,0,100,80);return c.toDataURL('image/png').split(',')[1];});
 await page.getByLabel('Choose a photo').setInputFiles({name:'demo.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.getByLabel('Describe the photo').fill('Test photo of a table setting');
 await page.getByRole('button',{name:'Share photo',exact:true}).click();
 await expect(page.getByRole('img',{name:'Test photo of a table setting'})).toBeVisible();
 const photos=await(await page.request.get('/api/restaurants/2/photos')).json();
 const photo=photos.find(p=>p.caption==='Test photo of a table setting');
 expect((await page.request.get('/api/photos/'+photo.id)).headers()['content-type']).toBe('image/jpeg');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.screenshot({path:'test-results/features-detail.png'});
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'☆ Achievements',exact:true}).click();
 await expect(page.locator('.badge.earned')).toHaveCount(3);
 await expect(page.locator('.badge').filter({hasText:'Local explorer'})).toContainText('1 / 3');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Gillies',exact:true}).click();
 await page.getByRole('button',{name:'Remove photo',exact:true}).click();
 await page.getByRole('button',{name:'Yes, remove',exact:true}).click();
 await expect(page.getByRole('img',{name:'Test photo of a table setting'})).toHaveCount(0);
 await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/features-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});

test('feature endpoints validate input and isolate account data',async({request,playwright})=>{
 expect((await request.put('/api/restaurants/4/favorite')).status()).toBe(401);
 expect((await request.post('/api/restaurants/4/photos',{data:{}})).status()).toBe(401);
 await request.post('/api/demo');
 await request.put('/api/restaurants/4/favorite');
 const review={rating:4,body:'A nice dinner with friends.',food:5,service:4,atmosphere:3};
 expect((await request.post('/api/restaurants/4/reviews',{data:review})).status()).toBe(200);
 expect((await request.post('/api/restaurants/4/reviews',{data:{...review,food:8}})).status()).toBe(400);
 const me=await(await request.get('/api/me')).json();
 const saved=(await(await request.get('/api/restaurants/4/reviews')).json()).find(r=>r.user_id===me.id);expect(saved.food).toBe(5);
 expect((await request.post('/api/restaurants/4/photos',{data:{image:'data:image/jpeg;base64,SGVsbG8=',caption:'Invalid file'}})).status()).toBe(400);
 const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
 expect((await request.post('/api/restaurants/4/photos',{data:{image,caption:'API test image'}})).status()).toBe(201);
 const photos=await(await request.get('/api/restaurants/4/photos')).json();const photo=photos.find(p=>p.user_id===me.id);
 const other=await playwright.request.newContext({baseURL:'http://127.0.0.1:5174'});
 await other.post('/api/demo');
 expect((await(await other.get('/api/restaurants')).json()).find(r=>r.id===4).favorite).toBe(false);
 expect((await other.delete('/api/photos/'+photo.id)).status()).toBe(403);
 expect((await request.delete('/api/photos/'+photo.id)).status()).toBe(200);
 await other.dispose();
});
