import { createRestaurantMap } from './map.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,restaurants=[],allRestaurants=[],activeRestaurant=null,authMode='login',searchVersion=0;
const modal=$('#modal');
const restaurantMap=createRestaurantMap(id=>details(id));
async function api(path,options={}){const res=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await res.json();if(!res.ok)throw new Error(data.error||'Please try again.');return data;}
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function openDialog(html){$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
$('.close-dialog').onclick=()=>modal.close();
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
function account(){
 $('#account-actions').innerHTML=user?`<span class="user-greeting">Hi, ${escape(user.name.split(' ')[0])}</span><button class="button small outline" id="sign-out">Sign out</button>`:`<button class="text-button" id="sign-in">Sign in</button><button class="button small primary" id="join">Join the table <span aria-hidden="true">↗</span></button>`;
 if(user)$('#sign-out').onclick=async()=>{try{await api('/logout',{method:'POST'});user=null;account();modal.close();notify('You’re signed out. See you at the table!');}catch(e){notify(e.message)}};
 else{$('#sign-in').onclick=()=>auth('login');$('#join').onclick=()=>auth('register');}
}
function auth(mode='login',after){
 authMode=mode;
 openDialog(`<div class="eyebrow">THERE’S A SEAT FOR YOU</div><h2 id="modal-title">${mode==='login'?'Welcome to the table.':'Make yourself at home.'}</h2><p class="dialog-intro">${mode==='login'?'Sign in to share your local discoveries.':'Create an account and share your first review.'}</p><form id="auth-form">${mode==='register'?'<label for="name">Display name</label><input id="name" name="name" autocomplete="nickname" minlength="2" maxlength="50" required>':''}<label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="email" maxlength="254" required><label for="password">Password</label><input id="password" name="password" type="password" minlength="8" maxlength="128" autocomplete="${mode==='login'?'current-password':'new-password'}" aria-describedby="password-hint" required><p class="field-hint" id="password-hint">Use 8–128 characters.</p><p class="form-error" id="auth-error" role="alert"></p><button class="button primary full" type="submit">${mode==='login'?'Sign in':'Create account'} <span aria-hidden="true">↗</span></button></form><p class="auth-switch">${mode==='login'?'New around here?':'Already have an account?'} <button class="text-button" id="switch-auth">${mode==='login'?'Create an account':'Sign in'}</button></p><div class="demo-divider"><span>JUST EXPLORING?</span></div><button class="button outline full" id="demo-login">Try the demo account <span aria-hidden="true">↗</span></button><p class="field-hint centered">No email needed. A fresh demo account, just for this session.</p>`);
 $('#switch-auth').onclick=()=>auth(mode==='login'?'register':'login',after);
 const finish=async value=>{user=value;account();modal.close();notify(`Welcome, ${user.name}!`);if(after)await after();};
 $('#auth-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#auth-error').textContent='';try{await finish(await api(mode==='login'?'/login':'/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}));}catch(error){$('#auth-error').textContent=error.message;}finally{button.disabled=false;}};
 $('#demo-login').onclick=async e=>{e.currentTarget.disabled=true;try{await finish(await api('/demo',{method:'POST'}));}catch(error){$('#auth-error').textContent=error.message;if($('#demo-login'))$('#demo-login').disabled=false;}};
}
function drawCatalog(){
 restaurantMap.update(restaurants);
 const sorted=[...restaurants];if($('#sort').value==='rating')sorted.sort((a,b)=>(b.rating||0)-(a.rating||0));if($('#sort').value==='name')sorted.sort((a,b)=>a.name.localeCompare(b.name));
 const query=$('#search').value.trim();$('#result-count').textContent=`${sorted.length} local ${sorted.length===1?'spot':'spots'}${query?` for “${query}”`:' to explore'}`;$('#clear-search').hidden=!query;$('#restaurant-grid').setAttribute('aria-busy','false');
 $('#restaurant-grid').innerHTML=sorted.length?sorted.map(r=>`<article class="restaurant-card theme-${r.id}"><div class="card-top"><div class="restaurant-monogram" aria-hidden="true">${r.initials}<span>✳</span></div><span class="card-index" aria-hidden="true">0${r.id} / LOCAL FINDS</span></div><div class="card-content"><p class="cuisine">${escape(r.cuisine)}</p><h3><button class="restaurant-link" data-restaurant="${r.id}">${escape(r.name)}</button></h3><p class="restaurant-description">${escape(r.description)}</p><p class="restaurant-location"><span aria-hidden="true">⌖</span> ${escape(r.area)}</p><div class="card-bottom"><span class="rating"><span class="rating-star" aria-hidden="true">★</span> <b>${r.rating?r.rating.toFixed(1):'New'}</b><span>${r.count} reviews</span></span><button class="card-arrow" data-restaurant="${r.id}" aria-label="View ${escape(r.name)} reviews">↗</button></div></div></article>`).join(''):`<div class="empty-state"><span aria-hidden="true">⌕</span><h3>No spots found this time.</h3><p>Try a restaurant name, a cuisine like Italian, or a location.</p><button class="button outline" id="reset-results">Show all restaurants</button></div>`;
 document.querySelectorAll('[data-restaurant]').forEach(b=>b.onclick=()=>details(Number(b.dataset.restaurant)));
 if($('#reset-results'))$('#reset-results').onclick=resetSearch;
}
async function loadCatalog(){const version=++searchVersion;$('#restaurant-grid').setAttribute('aria-busy','true');try{const result=await api('/restaurants?q='+encodeURIComponent($('#search').value));if(version!==searchVersion)return;restaurants=result;if(!$('#search').value.trim())allRestaurants=result;drawCatalog();}catch(e){if(version!==searchVersion)return;$('#result-count').textContent='The catalog couldn’t load.';$('#restaurant-grid').setAttribute('aria-busy','false');$('#restaurant-grid').innerHTML=`<div class="empty-state"><h3>Let’s try that again.</h3><p>${escape(e.message)}</p><button id="retry" class="button primary">Retry</button></div>`;$('#retry').onclick=loadCatalog;}}
function resetSearch(){$('#search').value='';loadCatalog();$('#search').focus();}
$('#search-form').onsubmit=e=>{e.preventDefault();loadCatalog();};
let debounce;$('#search').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(loadCatalog,180);};
$('#clear-search').onclick=resetSearch;$('#sort').onchange=drawCatalog;
const dateLabel=s=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
async function details(id){
 activeRestaurant=id;const r=allRestaurants.find(r=>r.id===id)||restaurants.find(r=>r.id===id);if(!r)return;
 openDialog('<h2 id="modal-title">Pulling up a seat…</h2><p role="status">Loading reviews.</p>');
 try{
  const reviews=await api(`/restaurants/${id}/reviews`);if(!modal.open||activeRestaurant!==id)return;
  const own=reviews.find(v=>v.user_id===user?.id);const average=reviews.length?(reviews.reduce((sum,v)=>sum+v.rating,0)/reviews.length).toFixed(1):'New';
  openDialog(`<div class="eyebrow">${escape(r.cuisine)} · ${escape(r.area)}</div><h2 id="modal-title">${escape(r.name)}</h2><p class="dialog-intro">${escape(r.description)}</p>${r.address?`<p class="detail-address">${escape(r.address)}</p><p><a class="website-link" href="https://www.google.com/maps/dir/?api=1&amp;destination=${encodeURIComponent(r.address)}" target="_blank" rel="noopener noreferrer">Get directions ↗<span class="sr-only"> (opens in a new tab)</span></a></p>`:''}<a class="website-link" href="${escape(r.website)}" target="_blank" rel="noopener noreferrer">Official restaurant website <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a><div class="review-summary"><div><span class="big-rating">${average}</span><span class="rating-star" aria-hidden="true">★</span><p>${reviews.length} community reviews</p></div><button class="button primary" id="write-review">${own?'Edit your review':'Write a review'} <span aria-hidden="true">↗</span></button></div><p class="sample-note">Reviews marked “Sample” are fictional demo content.</p><div id="review-editor"></div><h3 class="review-heading">Around the table</h3><div class="review-list">${reviews.length?reviews.map(v=>`<article class="review"><div class="review-header"><span class="avatar" aria-hidden="true">${escape(v.name.slice(0,1))}</span><div><h4>${escape(v.name)} ${v.user_id===user?.id?'<span class="you-label">You</span>':''}</h4><span class="review-date">${dateLabel(v.created)}${v.sample?' · Sample':''}</span></div><span class="review-stars" aria-label="${v.rating} out of 5 stars">${'★'.repeat(v.rating)}<span aria-hidden="true">${'☆'.repeat(5-v.rating)}</span></span></div><p>${escape(v.body)}</p></article>`).join(''):'<p class="dialog-intro">No reviews yet. Be the first to share your experience.</p>'}</div>`);
  $('#write-review').onclick=()=>user?reviewEditor(id,own):auth('login',()=>details(id).then(()=>$('#write-review')?.click()));
 }catch(e){openDialog(`<h2 id="modal-title">Reviews couldn’t load.</h2><p role="alert">${escape(e.message)}</p><button id="retry-details" class="button primary">Try again</button>`);$('#retry-details').onclick=()=>details(id);}
}
function reviewEditor(id,own){
 $('#review-editor').innerHTML=`<form id="review-form" class="review-form"><h3>${own?'Your experience, updated.':'How was your visit?'}</h3><fieldset><legend>Your overall rating <span class="required-label">(required)</span></legend><div class="rating-options">${[1,2,3,4,5].map(n=>`<label class="rating-option"><input type="radio" name="rating" value="${n}" ${own?.rating===n?'checked':''} required><span>${n} <span aria-hidden="true">★</span></span><span class="sr-only">${n===1?' star':' stars'}</span></label>`).join('')}</div></fieldset><label for="review-body">Your review</label><textarea id="review-body" name="body" rows="4" minlength="10" maxlength="1000" required aria-describedby="review-hint" placeholder="What should someone know before their first visit?">${escape(own?.body||'')}</textarea><div class="field-hint review-hints"><span id="review-hint">10–1,000 characters. Your name will appear with your review.</span><span id="character-count">${own?.body.length||0}/1000</span></div><p class="form-error" id="review-error" role="alert"></p><div class="editor-actions"><button class="button primary" type="submit">${own?'Save changes':'Publish review'} <span aria-hidden="true">↗</span></button><button class="text-button" id="cancel-review" type="button">Cancel</button>${own?'<button class="text-button delete-button" id="delete-review" type="button">Delete review</button>':''}</div><div id="delete-confirm"></div></form>`;
 $('#review-body').oninput=e=>$('#character-count').textContent=e.target.value.length+'/1000';
 $('#cancel-review').onclick=()=>{$('#review-editor').innerHTML='';$('#write-review').focus();};
 $('#review-form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);e.submitter.disabled=true;try{await api(`/restaurants/${id}/reviews`,{method:'POST',body:JSON.stringify({rating:Number(data.get('rating')),body:data.get('body')})});await loadCatalog();await details(id);notify(own?'Your review has been updated.':'Your review is at the table. Thanks for sharing!');}catch(error){$('#review-error').textContent=error.message;e.submitter.disabled=false;}};
 if(own)$('#delete-review').onclick=()=>{
  $('#delete-confirm').innerHTML='<div class="delete-confirm"><p>Delete your review? This cannot be undone.</p><button type="button" class="button primary" id="confirm-delete">Yes, delete my review</button> <button type="button" class="text-button" id="keep-review">Keep review</button></div>';
  $('#keep-review').onclick=()=>$('#delete-confirm').innerHTML='';
  $('#confirm-delete').onclick=async e=>{e.currentTarget.disabled=true;try{await api(`/restaurants/${id}/reviews`,{method:'DELETE'});await loadCatalog();await details(id);notify('Your review was deleted.');}catch(error){$('#review-error').textContent=error.message;if($('#confirm-delete'))$('#confirm-delete').disabled=false;}};
 };
 $('#review-editor input').focus();
}
async function myReviews(){
 if(!user)return auth('login',myReviews);
 openDialog('<h2 id="modal-title">Your reviews</h2><p role="status">Loading your local discoveries…</p>');
 try{const catalog=await api('/restaurants');const entries=await Promise.all(catalog.map(async r=>({r,review:(await api(`/restaurants/${r.id}/reviews`)).find(v=>v.user_id===user.id)})));
 openDialog(`<div class="eyebrow">YOUR SEAT AT THE TABLE</div><h2 id="modal-title">Your reviews</h2><p class="dialog-intro">The places you’ve tried. The stories you’ve shared.</p>${entries.some(e=>e.review)?entries.filter(e=>e.review).map(({r,review})=>`<article class="my-review"><h3>${escape(r.name)}</h3><p class="review-stars" aria-label="${review.rating} out of 5 stars">${'★'.repeat(review.rating)}</p><p>${escape(review.body)}</p><button class="text-button" data-edit="${r.id}">View or edit review ↗</button></article>`).join(''):'<div class="empty-state compact"><span aria-hidden="true">☆</span><h3>Your first discovery is waiting.</h3><p>Pick a local spot and tell the community about your visit.</p><button class="button primary" id="explore-from-reviews">Explore restaurants ↗</button></div>'}`);
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>details(Number(b.dataset.edit)));if($('#explore-from-reviews'))$('#explore-from-reviews').onclick=()=>{modal.close();$('#catalog').scrollIntoView();$('#search').focus();};
 }catch(e){openDialog(`<h2 id="modal-title">Your reviews couldn’t load.</h2><p role="alert">${escape(e.message)}</p><button class="button primary" id="retry-mine">Retry</button>`);$('#retry-mine').onclick=myReviews;}
}
$('#reviews-nav').onclick=myReviews;
$('#contribute').onclick=()=>{openDialog(`<div class="eyebrow">SHARE A LOCAL DISCOVERY</div><h2 id="modal-title">Where did you eat?</h2><p class="dialog-intro">Choose a restaurant to share your experience.</p><div class="restaurant-picker">${allRestaurants.map(r=>`<button class="picker-row" data-pick="${r.id}"><span>${escape(r.name)}<small>${escape(r.cuisine)}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div>`);document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>details(Number(b.dataset.pick)).then(()=>$('#write-review')?.click()));};
account();
Promise.all([api('/me').then(value=>{user=value;account();}),loadCatalog()]).catch(()=>notify('Could not restore your session. Please try signing in again.'));
